#!/usr/bin/env bash
# Configures localhost and facebook.com name resolution

{
  echo "127.0.0.2 localhost"
  echo "8.8.8.8 facebook.com"
  grep -vE 'localhost|facebook\.com' /etc/hosts
} > /tmp/hosts

cat /tmp/hosts > /etc/hosts
